import jsPDF from 'jspdf';
import { AnalysisReport } from '../types/analysis';

export const exportAnalysisReport = (report: AnalysisReport) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.width;
  const margin = 20;
  let yPosition = margin;

  // Helper function to add text with word wrapping
  const addText = (text: string, fontSize: number = 12, isBold: boolean = false) => {
    pdf.setFontSize(fontSize);
    if (isBold) {
      pdf.setFont('helvetica', 'bold');
    } else {
      pdf.setFont('helvetica', 'normal');
    }
    
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * (fontSize * 0.4) + 5;
    
    // Check if we need a new page
    if (yPosition > pdf.internal.pageSize.height - margin) {
      pdf.addPage();
      yPosition = margin;
    }
  };

  // Header
  addText('RESUME ANALYSIS REPORT', 20, true);
  addText(`Generated on: ${new Date().toLocaleDateString()}`, 10);
  yPosition += 10;

  // Basic Info
  addText('ANALYSIS DETAILS', 16, true);
  addText(`Target Role: ${report.target_domain.replace('-', ' ').toUpperCase()}`, 12);
  addText(`Version: ${report.version_name || 'Default'}`, 12);
  addText(`Analysis Date: ${new Date(report.created_at).toLocaleDateString()}`, 12);
  yPosition += 10;

  // Scores
  addText('PERFORMANCE SCORES', 16, true);
  addText(`Overall Score: ${report.analysis_results.score}/100`, 12, true);
  addText(`ATS Compatibility: ${report.analysis_results.ats_compatibility}/100`, 12);
  addText(`Grammar Score: ${report.analysis_results.grammar_score}/100`, 12);
  addText(`Readability Score: ${report.analysis_results.readability_score}/100`, 12);
  yPosition += 10;

  // Strengths
  addText('STRENGTHS', 16, true);
  report.analysis_results.strengths.forEach((strength, index) => {
    addText(`${index + 1}. ${strength}`, 11);
  });
  yPosition += 10;

  // Weaknesses
  addText('AREAS FOR IMPROVEMENT', 16, true);
  report.analysis_results.weaknesses.forEach((weakness, index) => {
    addText(`${index + 1}. ${weakness}`, 11);
  });
  yPosition += 10;

  // Improvement Tips
  addText('OPTIMIZATION RECOMMENDATIONS', 16, true);
  report.analysis_results.improvements.forEach((improvement, index) => {
    addText(`${index + 1}. ${improvement}`, 11);
  });
  yPosition += 10;

  // Skills
  addText('SKILLS ANALYSIS', 16, true);
  addText('Hard Skills:', 12, true);
  addText(report.analysis_results.hard_skills.join(', '), 11);
  yPosition += 5;
  addText('Soft Skills:', 12, true);
  addText(report.analysis_results.soft_skills.join(', '), 11);
  yPosition += 10;

  // Sections
  addText('RESUME STRUCTURE', 16, true);
  addText('Detected Sections:', 12, true);
  addText(report.analysis_results.sections_detected.join(', '), 11);
  if (report.analysis_results.missing_sections.length > 0) {
    yPosition += 5;
    addText('Missing Sections:', 12, true);
    addText(report.analysis_results.missing_sections.join(', '), 11);
  }
  yPosition += 10;

  // Issues
  if (report.analysis_results.formatting_issues.length > 0) {
    addText('FORMATTING ISSUES', 16, true);
    report.analysis_results.formatting_issues.forEach((issue, index) => {
      addText(`${index + 1}. ${issue}`, 11);
    });
    yPosition += 10;
  }

  if (report.analysis_results.grammar_issues.length > 0) {
    addText('GRAMMAR ISSUES', 16, true);
    report.analysis_results.grammar_issues.forEach((issue, index) => {
      addText(`${index + 1}. ${issue}`, 11);
    });
    yPosition += 10;
  }

  // JD Match Results
  if (report.jd_match_results) {
    addText('JOB DESCRIPTION MATCH ANALYSIS', 16, true);
    addText(`Match Percentage: ${report.jd_match_results.match_percentage}%`, 12, true);
    addText(`Role Fit Score: ${report.jd_match_results.role_fit_score}/100`, 12);
    yPosition += 5;
    
    addText('Matched Keywords:', 12, true);
    addText(report.jd_match_results.matched_keywords.join(', '), 11);
    yPosition += 5;
    
    addText('Missing Keywords:', 12, true);
    addText(report.jd_match_results.missing_keywords.join(', '), 11);
    yPosition += 10;
  }

  // Summary
  addText('EXECUTIVE SUMMARY', 16, true);
  addText(report.analysis_results.summary, 11);

  // Footer
  yPosition = pdf.internal.pageSize.height - margin;
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Generated by Resume Analyzer & Optimizer', margin, yPosition);

  // Save the PDF
  const fileName = `resume-analysis-${report.target_domain}-${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(fileName);
};